cityofaustin/joplin

joplin/base/admin.py, joplin/settings.py, setup.cfg
Added flake8 checking and fixed pep8 errors
=> Fix pep8 errors

deploy/requirements.txt, joplin/settings.py
Basic CORS config for api access on local janis
We'll want to definitely tweak this as we build deeper.
=> cors config

fixtures/initial.json
This uses the actual content we're going to start with
=> Use fixture data based on real content

README.md, deploy/requirements.txt, joplin/api/apps.py, joplin/api/schema.py, joplin/settings.py, joplin/static/js/admin.js, joplin/urls.py
Here's a taste of getting live data as well as preview data
=> Add graphql support

README.md
Noticed the the port listed as 800 and figured it wasn't right. All good now!
=> Fix typo in README. Changed port from 800 to 8000 on line 25.

README.md
Updated the Background in the README, because "bla bla bla" was unhelpful.
=> Filled in Background

app.json, heroku.yml
There's some new build stuff from Heroku that might allow us to create review apps, so I'm experimenting with it.
Docs are at https://devcenter.heroku.com/articles/heroku-yml-build-manifest
=> Experiment with heroku docker builds

joplin/base/wagtail_hooks.py, joplin/settings.py, joplin/static/js/analytics.js
Oh look, a gif showing the session being replayed in fullstory
=> Add Fullstory

fixtures/contacts.yaml
Fixes cityofaustin/techstack#159
=> Use the correct hours for Recycle & Reuse Center

fixtures/locations.yaml
Part of cityofaustin/techstack#207
=> Use correct name for Recycle & Reuse Center

fixtures/contacts.yaml, fixtures/services/hazardous-waste-dropoff.yaml, fixtures/services/pickup-free-paint.yaml
=> Use correct name for Location

fixtures/services/pickup-free-paint.yaml, fixtures/services/trash-recycling-pickup.yaml
=> Fix Arabic translations for the trash & recycling pickup page

docker-entrypoint.sh, joplin/base/management/commands/loadcontent.py
Also added theme loading to server startup
=> Load theme when creating topic

joplin/api/schema.py
This endpoint is to deliver draft data to Janis for use in previewing page content in Joplin.
closes https://github.com/cityofaustin/techstack/issues/479
related to https://github.com/cityofaustin/techstack/issues/478
=> Add revisions endpoint

joplin/static/css/preview.css, joplin/templates/wagtailadmin/pages/edit.html
works on https://github.com/cityofaustin/techstack/issues/467
related to overall https://github.com/cityofaustin/techstack/issues/417
=> Iterate towards a better sidebar

README.md, deploy/requirements.txt, joplin/base/signals.py, joplin/settings.py, scripts/serve-local.sh
I've noticed it takes about 10 minutes for the new build to finish. I started
to add the ability to show the build progress via the UI, but wasn't sure what
that workflow should look like.
Fixes cityofaustin/techstack#480
=> Kickoff Heroku build when pages are published/unpublished

README.md, deploy/requirements.txt, joplin/base/signals.py, joplin/base/wagtail_hooks.py, joplin/settings.py, joplin/static/js/editor.js, joplin/templates/base.html, joplin/templates/wagtailadmin/pages/edit.html, scripts/serve-local.sh
Redoing this bc I didn't realize the first PR was against a branch other than `master`
=> Kickoff build

app.json, joplin/base/models.py, joplin/static/css/editor.css, joplin/static/css/preview.css, joplin/static/js/admin.js, joplin/templates/wagtailadmin/pages/edit.html
https://github.com/cityofaustin/techstack/issues/542
=> Bs share button improvements

joplin/base/models.py, joplin/static/css/editor.css, joplin/static/css/preview.css, joplin/static/js/admin.js
https://github.com/cityofaustin/techstack/issues/533
https://github.com/cityofaustin/techstack/issues/571
=> Bs edit page improvements

joplin/api/schema.py, joplin/base/models.py, joplin/js/editor.js
Closes https://github.com/cityofaustin/techstack/issues/634
This is a starting point for a shared base model.
@briaguya @mateoclarke -- I'm not 100% on how inheritance works in Django so feedback plz. 
Required related changes in Janis here: https://github.com/cityofaustin/janis/pull/268
=> Base Page Model

joplin/js/CreateContentModal/ButtonBar.js, joplin/js/CreateContentModal/ChooseTitleStep.js, joplin/js/CreateContentModal/index.js, joplin/package.json, joplin/templates/wagtailadmin/pages/create.html
* Fix "Save Draft" button on create page https://github.com/cityofaustin/techstack/issues/686
* Fix header styling on create page https://github.com/cityofaustin/techstack/issues/686
* Create Content Modal:
* Clear data in fields and radio buttons "close" https://github.com/cityofaustin/techstack/issues/696
* Fix typo https://github.com/cityofaustin/techstack/issues/700
* Always say "characters remaining" instead of switching from "character limit" https://github.com/cityofaustin/techstack/issues/701
* Add prettier config so we don't fight defaults https://github.com/cityofaustin/techstack/issues/738
=> Addressing bugs from Joplin QA

joplin/base/signals.py, joplin/settings.py
I've tested this by merging it into production and it is working in prod already. After we merge into master we should verify that it's working in staging.
=> Deploy prod to prod and staging to staging

joplin/css/editor.scss, joplin/js/editor.js
Everything in https://github.com/cityofaustin/techstack/issues/834 not covered by https://github.com/cityofaustin/techstack/issues/836 or https://github.com/cityofaustin/techstack/issues/837
=> Service Page UI Fixes

joplin/js/CreateContentModal/index.js, joplin/package.json, joplin/yarn.lock
This simply hides the modal while we're waiting to redirect to the newly created page edit screen. We still have the rest of the page greyed out during this time.
=> Prevent creating duplicate pages with modal

joplin/base/views/joplin_views.py
Resolves https://github.com/cityofaustin/techstack/issues/896
=> Set authors on newly created content

.gitignore, README/images.md, README/pg_restore.md
Some Documentation related to cityofaustin/techstack#1408
Frontend PR: https://github.com/cityofaustin/janis/pull/329
=> add documentation

deploy/requirements.txt, joplin/settings.py, joplin/urls.py
* Add [django-smuggler](https://github.com/semente/django-smuggler) to more easily backup/restore data between environments.
=> Add django-smuggler

joplin/base/signals.py, joplin/settings.py
This PR adds the trigger functionality to Joplin (prod and staging). Using environment variables (set up in Heroku) it will determine whether build Janis staging (from Joplin staging) and Janis prod (from Joplin prod).
=> Added Trigger for AWS Builds

joplin/templates/wagtailadmin/base.html
resolves https://github.com/cityofaustin/techstack/issues/926
=> functional but ugly

joplin/base/models.py
Resolves https://github.com/cityofaustin/techstack/issues/1958
Resolves https://github.com/cityofaustin/techstack/issues/1960
=> Quick fix for titles

deploy/requirements.txt
So testing this on a local build and it built, I also loaded data and didn't see anything immediately wrong.
=> be bold, upgrade straight to 2.5.1

joplin/css/pages/edit.scss, joplin/templates/wagtailadmin/pages/edit.html
hacky css + html FTW
Some later design questions to handle for sure, i played around with the styling of the language select thing, but we should really think it through w/design
Some variation of:
=> change language select to toggles, write it as its own semantic section

joplin/css/pages/edit.scss
Fixes https://github.com/cityofaustin/techstack/issues/1938
=> tweak language select per Tori

joplin/css/preview.scss, joplin/settings.py, joplin/templates/wagtailadmin/pages/edit.html
fixes https://github.com/cityofaustin/techstack/issues/1930
=> format url copied window to match spec

joplin/base/signals.py
In Wagtail's signals, `instance.owner.email` always defaults to `admin@austintexas.io`, we need to be able to retrieve the actual email of the person who published the session, regardless of the identity of the owner.
=> Updated signals for session's user email

docker-entrypoint.sh, joplin/css/layouts/headers.scss
Resolves https://github.com/cityofaustin/techstack/issues/2249
=> Fix styles/scripts in review apps

app.Dockerfile, docker-compose.janis.yml, docker-entrypoint.assets.sh, joplin/base/models.py, joplin/css/preview.scss, joplin/js/editor.js, joplin/package.json, joplin/static/js/admin.js, joplin/templates/wagtailadmin/pages/edit.html, joplin/templates/wagtailadmin/shared/sidebar-preview.html, joplin/yarn.lock
Surprisingly big issue, I'd love to have ya'll thoughts on this. If we like this pattern, we can use it going forward.
Ref: https://github.com/cityofaustin/techstack/issues/1959
To QA: run it locally. See if you can do a "Mobile Preview", "Preview", and "Share" in Spanish.
Bonus changes:
- gunicorn reloads, so you can see python changes without restarting your container
- node-sass re-compiling happens automatically in the assets docker container
- the big one: we now have any easy way to move django objects into javascript
From edit.html:
```
<script>
// Load this before render_bundle to use django vars inside javascript
var previewUrlData = {};
try {
// get python dictionary into valid JSON format
previewUrlData=JSON.parse("{{page.preview_url_data|escapejs}}".replace(/\'/g, '\"'));
} …
```
=> Issue 1959: translate previews and sharing

joplin/templates/wagtailadmin/pages/revisions/list.html
Fixes https://github.com/cityofaustin/techstack/issues/2094
=> remove page author

joplin/css/admin.scss, joplin/css/editor.scss, joplin/js/admin.js, joplin/js/editor.js
Fixes https://github.com/cityofaustin/techstack/issues/2255
=> move banner to top, increase timeout, reduce width to fit grid better

docker-entrypoint.sh, joplin/base/wagtail_hooks.py, joplin/css/layouts/headers.scss, joplin/templates/wagtailadmin/pages/listing/_table_headers_explore.html
Fixes https://github.com/cityofaustin/techstack/issues/2230
=> 2230 fix search

joplin/base/models.py
Fixes https://github.com/cityofaustin/techstack/issues/2236
=> Fix "view live" links

joplin/css/admin.scss
Fixes https://github.com/cityofaustin/techstack/issues/1944
=> 1944 logout menu alignment

joplin/settings.py, joplin/urls.py
adds django's auto generated documentation, helpful for describing methods and models
check it out at admin/docs !
=> uses django's doc generator to give us a handy refrence for stuff

deploy/requirements.txt, joplin/settings.py, joplin/templates/wagtailadmin/base.html, joplin/urls.py
Fixes https://github.com/cityofaustin/techstack/issues/2266
timeout can be adjusted in settings.py, set super short now so its easy to test
=> implements django_session_security

joplin/base/wagtail_hooks.py, joplin/css/layouts/left_sidebar_nav.scss, joplin/templates/wagtailadmin/base.html
Oops, I fixed https://github.com/cityofaustin/techstack/issues/2510
=> adds material icons and mildy refactors the way we build the menu

joplin/base/wagtail_hooks.py, joplin/css/admin.scss, joplin/css/editor.scss, joplin/css/layouts/listing.scss, joplin/js/EditPage/menuActiveState.js, joplin/templates/wagtailadmin/pages/edit.html
Resolves https://github.com/cityofaustin/techstack/issues/2632
=> 2632 fix skinny step

joplin/css/editor.scss, joplin/templates/wagtailadmin/pages/edit.html
Resolves https://github.com/cityofaustin/techstack/issues/2605
=> Only hide the footer on our Page edit screen

joplin/base/wagtail_hooks.py, joplin/css/editor.scss, joplin/css/layouts/listing.scss, joplin/templates/wagtailadmin/pages/edit.html
Resolves https://github.com/cityofaustin/techstack/issues/2558
=> 2558 remove notes link

joplin/base/wagtail_hooks.py, joplin/css/admin.scss, joplin/css/editor.scss, joplin/css/layouts/listing.scss, joplin/js/EditPage/menuActiveState.js, joplin/templates/wagtailadmin/pages/edit.html
Resolves https://github.com/cityofaustin/techstack/issues/2606
edit: whoops, I was still on this branch when I fixed
Fixes https://github.com/cityofaustin/techstack/issues/2657
=> 2606 remove copy content from

joplin/base/wagtail_hooks.py, joplin/css/admin.scss, joplin/css/editor.scss, joplin/css/layouts/listing.scss, joplin/js/EditPage/menuActiveState.js, joplin/templates/wagtailadmin/pages/edit.html
Resolves https://github.com/cityofaustin/techstack/issues/2582
=> 2582 add delete to menu

joplin/base/wagtail_hooks.py, joplin/css/admin.scss, joplin/css/editor.scss, joplin/css/layouts/listing.scss, joplin/js/EditPage/menuActiveState.js, joplin/templates/wagtailadmin/pages/edit.html
Resolves https://github.com/cityofaustin/techstack/issues/2654
=> 2654 fix wonky scrolling

joplin/base/wagtail_hooks.py, joplin/css/admin.scss, joplin/css/editor.scss, joplin/css/layouts/listing.scss, joplin/js/EditPage/menuActiveState.js, joplin/templates/wagtailadmin/pages/edit.html
Resolves https://github.com/cityofaustin/techstack/issues/2579
=> 2579 fix draft button

joplin/base/wagtail_hooks.py
Fixes https://github.com/cityofaustin/techstack/issues/2510
=> Home to Pages

joplin/css/editor.scss
resolves https://github.com/cityofaustin/techstack/issues/2699
=> made the primary header z-indexed above the secondary

joplin/base/models/janis_page.py, joplin/base/models/topic_page.py
I missed Python too much so here's a stab at something more compact and a step towards something more abstract, given the fluctuating nature of our IA 
This supersedes https://github.com/cityofaustin/joplin/pull/350 
and https://github.com/cityofaustin/joplin/pull/349
=> 2856 and now for something completely different

joplin/base/signals.py
resolves https://github.com/cityofaustin/techstack/issues/2703
=> add receivers for post_save on all the snippets we have

.circleci/scripts/create_review_app.sh, .circleci/scripts/set_pr_vars.sh, README.md, joplin/base/models/janis_page.py
Fixes https://github.com/cityofaustin/techstack/issues/2999
=> adds additional url construction handiling

joplin/css/editor.scss, joplin/js/EditPage/richTextPlaceholder.js, joplin/js/editor.js
I condensed some of the language code down. It probably needs more work and testing, but the idea is not to have very similar code chunks for each particular admin UI object and just find all the language labels as they are and change them as needed.
=> 2827 js refactor

joplin/css/layouts/left_sidebar_nav.scss, joplin/js/CreateContentModal/index.js
=> Change create content copy

joplin/settings.py
hide options from info pages -> prod
=> Master -> Prod

joplin/css/admin.scss, joplin/js/editor.js
fixes https://github.com/cityofaustin/techstack/issues/3118
fixes https://github.com/cityofaustin/techstack/issues/3117
=> fix header regressions

joplin/base/wagtail_hooks.py, joplin/css/editor.scss
https://github.com/cityofaustin/techstack/issues/3029
Try making/unmaking buttons in service page steps. 
https://joplin-pr-3029-persist-button.herokuapp.com/
=> button persists!

joplin/api/schema.py
Joplin side of: https://github.com/cityofaustin/techstack/issues/3082
=> guide page previews

joplin/base/wagtail_hooks.py
Fix attribute error
* [Issue Link](https://github.com/cityofaustin/techstack/issues/3006)
go to:
{joplin url}/admin/pages/
{joplin url}/admin/pages/search/?q=
if they don't give us an error we're gold
* [Deployed Link]() TODO
=> fix blank search query error

joplin/base/models/__init__.py, joplin/base/models/site_settings.py, joplin/base/wagtail_hooks.py
... Please include a summary of the change and what it fixes.
* [Issue Link]()
* [Janis Related Pull Request Link]()
... how can this be tested ?
* [Deployed Link]()
=> move site setting into base.models

joplin/settings.py
... Please include a summary of the change and what it fixes.
* [Issue Link]()
* [Janis Related Pull Request Link]()
... how can this be tested ?
* [Deployed Link]()
=> show panels

joplin/base/models/janis_page.py
... Please include a summary of the change and what it fixes.
Fixes # https://github.com/cityofaustin/techstack/issues/3199
Should be able to enter and update slugs for any language and see them saved. 
* https://joplin-pr-3199-duplicate-slug.herokuapp.com/admin/login/
=> 3199-Fix duplicate slugs showing

joplin/base/context_processors.py, joplin/css/theme-override.scss, joplin/css/variables.scss, joplin/js/admin.js, joplin/js/theme.js, joplin/templates/wagtailadmin/base.html, joplin/templates/wagtailadmin/login.html, joplin/webpack.base.js
... Please include a summary of the change and what it fixes.
Fixes # https://github.com/cityofaustin/techstack/issues/2963
Colors should reflect on local, staging, or PR, but not on Prod (you could test this by inverting the flag or merging to prod)
=> 2963 themes

joplin/base/views/joplin_views.py
=> should do the trick for now

joplin/templates/wagtailadmin/chooser/browse.html
=> Is this good enough?

joplin/settings.py
fix https://github.com/cityofaustin/techstack/issues/3407
=> try fixing it

joplin/base/models/service_page.py
See title
http://joplin-pr-3120-step-ols.herokuapp.com/admin/
=> 3120 remove ordered lists from service steps

joplin/base/models/service_page.py
=> add 'ol' back

.circleci/scripts/check_app_status.py, Pipfile, Pipfile.lock, joplin/settings.py
https://github.com/cityofaustin/techstack/issues/3503
yolo merge, got production bugs to monitor
=> Issue 3503: memory bugs

.circleci/docker/joplin-base.Dockerfile, .circleci/vars/branch_overrides.py, .circleci/vars/heroku_pr_vars.py, app.Dockerfile
https://github.com/cityofaustin/techstack/issues/3503
yolo merge
=> set WEB_CONCURRENCY as configurable env var

.circleci/vars/heroku_pr_vars.py, Pipfile, Pipfile.lock, README.md, joplin/settings.py, joplin/urls.py, locustfile.py, template.env
=> Add load testing and performance monitorization!

Pipfile.lock, joplin/settings.py
trying to conditionally include silk as an installed app causes problems
=> tweak so not having silk installed dosen't break builds

.circleci/cleanup/README.md, .circleci/cleanup/build_zappa_settings.py, .circleci/cleanup/deploy.sh, .circleci/cleanup/main.py, README.md
=> 2780 clean up 2

joplin/js/editor.js
=> 3623 Translated nested Streamfields broken on wagtail 2.7

.circleci/scripts/check_app_status.py
https://austininnovation.slack.com/archives/G82KEHEQZ/p1576866871001500
=> * crossing fingers emoji *

README.md, joplin/base/models/constants.py
Adding the add document button to the rich text field
=> 3537 - add documents to the rich text field

scripts/clean_heroku_pipeline.py
First stab at the first part of https://github.com/cityofaustin/techstack/issues/2780
=> behold, a script

.circleci/vars/heroku_pr_vars.py, README.md
Adds documentation to link to coa-joplin-cleanup repo.
https://github.com/cityofaustin/techstack/issues/2780
=> add documentation for coa-joplin-clean-up

gunicorn.conf.py
=> Master -> Prod (3181 only)

joplin/js/CreateContentModal/ChooseTitleStep.js
Change the copy in the page title chooser
=> 3444 - change joplin microcopy

joplin/base/management/commands/load_joplin_data.py
https://github.com/cityofaustin/techstack/issues/3719
=> fix dummy typo

joplin/api/schema.py
=> just the fix for the error

.circleci/config.yml
The docker image for postgres that CircleCI uses was recently updated to require a password parameter. 
https://github.com/docker-library/postgres/issues/681
Does the build pass on CircleCI?
=> add password to circleci config

Pipfile, Pipfile.lock, joplin/base/wagtail_hooks.py, joplin/settings.py
Upgrades Wagtail, does some minor tweaks to maintain compatibility with embeds, and also hides the 'Reports' section of the menu, which will show you any pages you've locked from editing. 
Deployed at: https://dashboard.heroku.com/apps/joplin-pr-3912-wagtail-28
=> 3912 wagtail 28

.circleci/config.yml, joplin/api/schema.py
This is the joplin part of the Events List view on Janis. I needed to adjust the query so events would be a) return after a certain date, and b) in date order. I set it up so we can also return events before a certain date and the reverse date order, for when we eventually show past events. 
```
query getEventPage($id: ID, $date_Lte: Date, $date_Gte: Date) {
allEventPages(orderBy:"date", id:$id, date_Lte:$date_Lte, date_Gte:$date_Gte) {
edges {
node { }
}
}
}
```
adjust the `getEventPage` query by adding `orderBy: "date"` for ascending order or `orderBy: "-date"` for descending. 
date_Lte returns dates "less than or equal to" and Gte is greater than or equal to. Date are sent in "2020-03-02" format.
https://django-filter.readthedocs.io/en/master/ref/filterset.html#declaring-filterable-fiel …
=> 3817 - schema adjustments for event list

joplin/api/schema.py
In order to filter events if they are canceled or not, I needed to add it to the schema. 
Check in `api/graphiql` that you can toggle based on canceled
=> 3818- home pages events filter on canceled

joplin/events/models.py
Copy change for events from Long Description to Description.
=> 4001 - copy change on joplin

gunicorn.conf.py, joplin/settings.py
Performance testing is hairy, I did a lot of research on this for our situation. 
This tweaks the settings we just merged to get us a little more performance, but also with some safe defaults we can fall back onto if something breaks.
=> Gunicorn tweaks

joplin/base/models/official_documents_page.py
https://github.com/cityofaustin/techstack/issues/4075
=> uploading official_documents_page now works with new department groups

README.md, joplin/api/schema.py, joplin/settings.py
Addresses https://github.com/cityofaustin/techstack/issues/4042, unpublished page still appearing as a link on topic pages. I have a janis branch that filters top pages based on if they live or not, but I needed this joplin to be able to resolve `live` for top pages. 
I also filtered department and topic pages to not be added to the site structure if they aren't live, I found ~6 pages on prod that weren't live but still in the site structure. 
[Janis Related Pull Request Link](https://github.com/cityofaustin/janis/pull/720)
https://alpha.austin.gov/en/parks-and-recreation/ is in draft form, but you can see it
https://janis-4042-unpub-page.netlify.com/en/parks-and-recreation/ 404s
topicpage: https://alpha.austin.gov/en/health-safety/health-prevention/health-classes-and-resources/ …
=> 4042 - unpublished pages still appearing/ 

.circleci/vars/branch_overrides.py
I'm going to turn this on for now
=> load dummy data on v3 pr app

joplin/base/management/commands/load_joplin_data.py, joplin/base/wagtail_hooks.py, joplin/pages/service_page/fixtures/__init__.py, joplin/pages/service_page/fixtures/helpers/components.py, joplin/pages/service_page/fixtures/test_cases/new_contact.py, joplin/pages/service_page/tests.py
gets a little bit of contact stuff working in fixtures,
before building out the rest of it I'm going to get location pages in place
=> Service page with contact fixture

.circleci/vars/branch_overrides.py, joplin/api/schema.py, joplin/pages/topic_page/models.py
Pages on janis need to get their departments
and topics need to get their parent topic collections
https://joplin-pr-4224-resolve-dept.herokuapp.com/api/graphql
QUERY:
```
query allPagesQuery {
allPages {
edges {
node {
janisUrls
departmentpage {
id
}
topiccollectionpage {
id
}
janisbasepagewithtopiccollections {
id
topicpage {
id
title
slug
topiccollections {
id
title
slug
}
}
}
janisbasepagewithtopics {
id
servicepage {
id
janisUrl
departments {
id
title
slug
}
}
}
}
}
}
}
```
the database has: 
dept page: muni court
topic collection page: cititaions and registrations
with a topic: parking tickets
and the top page: how to pay a fine
=> resolve departments and topic collections

.circleci/scripts/helpers.sh
=> maybe fix unknown blob circleci issue

.circleci/scripts/build_image.sh, .circleci/scripts/helpers.sh
=> only push joplin images to heroku, not dockerhub

joplin/api/schema.py
https://github.com/cityofaustin/techstack/blob/master/changelogs/joplin.md#v283
=> v2.8.3 master => prod hotfix

joplin/api/schema.py
I forgot a critical missing piece that made the user resolver work.
=> V3 users hotfix

.circleci/vars/branch_overrides.py, joplin/base/management/commands/load_joplin_data.py, joplin/pages/official_documents_page/fixtures/__init__.py, joplin/pages/official_documents_page/fixtures/helpers/components.py, joplin/pages/official_documents_page/fixtures/helpers/create_fixture.py, joplin/pages/official_documents_page/fixtures/test_cases/kitchen_sink.py, joplin/pages/official_documents_page/management/commands/load_test_official_documents_pages.py, joplin/pages/official_documents_page/tests.py
add a fixture for an official docs page with a document on it
go here http://joplin-pr-official-docs-fixtur.herokuapp.com/admin/pages/11/edit/#tab-content
see that the document on that page exists here https://joplin-austin-gov-static.s3.amazonaws.com/review/official-docs-fixture/media/documents/filename.txt
=> Official docs fixture

joplin/pages/event_page/models.py, joplin/pages/event_page/tests.py, joplin/snippets/theme/fixtures/test_cases/kitchen_sink.py
=> Event page url error

joplin/snippets/theme/fixtures/test_cases/kitchen_sink.py
=> this was causing issues

joplin/api/schema.py
=> spell document correctly

.circleci/vars/branch_overrides.py, joplin/api/schema.py, joplin/pages/official_documents_page/fixtures/test_cases/kitchen_sink.py
* update kitchen sink documents to have required data for publish
* add preview_janis_instance to PageRevisionNode (for contextual nav on previews)
this janis works with it https://github.com/cityofaustin/janis/pull/733
http://joplin-pr-fixtures-and-preview.herokuapp.com/
=> Fixtures and previews

joplin/pages/service_page/factories.py, joplin/pages/service_page/fixtures/__init__.py, joplin/pages/service_page/fixtures/helpers/components.py, joplin/pages/service_page/fixtures/test_cases/dynamic_content_list.py, joplin/pages/service_page/fixtures/test_cases/kitchen_sink.py, joplin/pages/service_page/fixtures/test_cases/step_with_options.py, joplin/pages/service_page/fixtures/test_cases/steps_2.py, joplin/pages/service_page/fixtures/test_cases/steps_with_appblocks.py, joplin/pages/service_page/tests.py
before, if we tried to import https://janis.austintexas.io/en/preview/services/UGFnZVJldmlzaW9uTm9kZTozNDA3 we would get some nasty errors. There is now test data to account for this and a passing test.
see test passing, or run locally and try importing https://janis.austintexas.io/en/preview/services/UGFnZVJldmlzaW9uTm9kZTozNDA3
=> import service pages with dynamic content lists

.circleci/vars/branch_overrides.py, joplin/api/content_type_map.py, joplin/api/schema.py
I was using the wrong id and also the wrong nodes for the contextual nav
=> 4273 correct ids

joplin/pages/service_page/factories.py, joplin/pages/service_page/fixtures/__init__.py, joplin/pages/service_page/fixtures/helpers/components.py, joplin/pages/service_page/fixtures/test_cases/kitchen_sink.py, joplin/pages/service_page/fixtures/test_cases/steps_with_location.py, joplin/pages/service_page/tests.py
the importer is currently struggling with steps with locations, until we get that storted, let's just skip over them so:
* we can edit all of the pages we import in joplin
* we can query for steps in janis
=> 4280 skip step with location

joplin/api/schema.py
Merge https://github.com/cityofaustin/joplin/pull/682 into v3
`isLatest`, `isLive`, and `pageType` [can be queried](https://joplin-pr-latest-revision-mast.herokuapp.com/api/graphiql#query=%7B%0A%09allPageRevisions%20%7B%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20isLive%0A%20%20%20%20%20%20%20%20isLatest%0A%20%20%20%20%20%20%20%20pageType%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) on page revision nodes
=> Latest revision master to v3

joplin/api/schema.py
https://github.com/cityofaustin/techstack/issues/4304
Importer doesn't like them, and we aren't using them in v3, so let's ditch em.
This requires a janis change: https://github.com/cityofaustin/janis/pull/742
=> Remove map blocks from api

joplin/base/signals/publish_v3.py
=> just always rebuild for now

.circleci/vars/branch_overrides.py, joplin/api/schema.py
Resolve (and orderby filter etc) the correct documents, not all the documents. 
linked janis is: https://janis-v3-4340-official-documents.netlify.app/
=> 4340 official documents resolver

joplin/pages/base_page/models.py, joplin/pages/department_page/models.py, joplin/pages/event_page/models.py, joplin/pages/location_page/models.py, joplin/pages/topic_collection_page/models.py, joplin/pages/topic_page/models.py
Janis doesn't know what to do with localized urls yet, this makes it so we're only sending english to it https://github.com/cityofaustin/techstack/issues/4347
already merged this into import-everything, https://janis-v3-build-everything.netlify.app/es/housing-utilities/recycling-trash-and-compost/household-waste/test-guide-en should not 404
=> just hardcode to slug_en for now

joplin/pages/topic_collection_page/models.py
=> missed a spot

joplin/importer/queries.py
=> just add it to the query

joplin/pages/home_page/models.py
gotta send a janis_branch to publisher if you want to publish.
=> set correct publish_janis_branch for staging and prod

.circleci/config.yml
=> v 3.0.1 master => production

.circleci/config.yml
https://github.com/cityofaustin/techstack/blob/master/changelogs/joplin.md#v321
=> master => prod v3.2.0

.circleci/vars/branch_overrides.py, joplin/base/signals/janis_build_triggers.py, joplin/css/pages/edit.scss, joplin/joplin_UI/pageStatus.scss, joplin/settings.py, joplin/templates/joplin_UI/pageStatus/publishing_modal.html, joplin/templates/joplin_UI/pageStatus/unpublishing_modal.html, joplin/templates/wagtailadmin/pages/edit.html
=> 4356 queue banner

joplin/base/templatetags/joplin_tags.py
https://github.com/cityofaustin/techstack/issues/4600
New routes in our digital-services-style-guide!
So we need to update our `STYLEGUIDE_PAGES` for our styleguide sidebar.
Cool!
Also, we're adding the form container style guide, which we didn't have inserted before.
=> 4600 styleguide

joplin/pages/news_page/models.py
Changing copy for news help text
https://app.abstract.com/projects/bbe34f6b-7080-4dcd-9fa9-d8e30d8f6128/branches/e89776e3-22dd-427b-8410-423549ceb8a9/commits/1eadf1dddb9f8a65df02f6e83218fbc4e2561e42/files/2599e46f-b4d5-4147-8777-c09594859afa/layers/51f95752-f28d-4f36-95f8-10fb300b81b0?mode=design&sha=1eadf1dddb9f8a65df02f6e83218fbc4e2561e42
https://github.com/cityofaustin/techstack/issues/4720
https://joplin-pr-4720-news-copy.herokuapp.com/admin/pages/27/edit/#tab-content
=> 4720 change copy on news page help text

joplin/base/views/site_search.py
https://github.com/cityofaustin/techstack/blob/master/changelogs/joplin.md#v3121
=> v3.12.1 master => prod

joplin/base/models/constants.py, joplin/pages/information_page/models.py
This was previously merged to master/production but got left off when a PR was reverted. I'm replacing the functionality that went missing.
=> Add images to rich text fields on joplin

joplin/pages/event_page/models.py, joplin/pages/official_documents_page/models.py
=> Prod to 3.14.1

joplin/pages/department_page/models.py
We want to link to the annual report without losing any other links
=> update related pages to 5 on dept pages

joplin/pages/department_page/models.py, joplin/pages/official_documents_page/models.py
=> production to 3.14.2
