cityofaustin/joplin

README.md, joplin/base/blocks.py, joplin/base/models.py
The [wagtail docs recommend custom serializers](http://docs.wagtail.io/en/v1.13.1/advanced_topics/api/v2/configuration.html#custom-serialisers) if you need to have
a custom representation.
However, this doesn't work for StreamField blocks. They [have to be handled
separately](https://stackoverflow.com/questions/41956709/custom-representation-of-streamfield-in-rest-api) by overriding `get_api_representation` for the block.
This approach seems kinda weird but is the only way it'll work currently.
With this change you'll see both the `extra_content.application_block` values as well as `theme.text`
```sh
curl -Ss 'http://localhost:8000/api/pages/4/?fields=content,extra_content,theme(text)'  | jq '{theme:.theme,extra_content:.extra_content[0]}'
```
```json
{
"theme": {
"id": 1,
"meta": { …
```
=> Serialize StreamField snippets

Dockerfile, joplin/settings.py, scripts/deploy.sh
Little deets:
- Add necessary `ALLOWED_HOSTS` so django doesn't cry when a request comes from heroku
- Modify Dockerfile to support `PORT` environment variable, which is required by heroku
=> Add deploy script for heroku

joplin/api/schema.py
Implements cityofaustin/joplin#38
```graphql
{
servicePage(pk: 5) {
id
slug
title
related {
id
slug
title
}
}
}
```
```json
{
"data": {
"servicePage": {
"id": "U2VydmljZVBhZ2VOb2RlOjU=",
"related": [
{
"id": "U2VydmljZVBhZ2VOb2RlOjQ=",
"slug": "holiday-tree-recycling",
"title": "Recycle your Christmas treeeeeeeeeeee"
},
{
"id": "U2VydmljZVBhZ2VOb2RlOjY=",
"slug": "residential-curbside-collection-schedule",
"title": "Look up your Trash, Recycling, and Compost Days"
},
{
"id": "U2VydmljZVBhZ2VOb2RlOjc=",
"slug": "residential-bulk-collection",
"title": "Get Ready for Bulk Item Pick-up"
}
],
"slug": "dropoff",
"title": "Pick Up Free Household Items from the ReUse Store"
}
}
}
```
=> Add related services for cityofaustin/joplin#38

README.md, fixtures/base.json, fixtures/pages.json
I was using the formatter in VSCode, but we should stick to the formatting used by the data dump tool so it's consistent across developers. I also added a little more context in the README about dumping which sets of data.
=> Format fixtures

joplin/static/js/admin.js
Access `document.cookie` inside was blocked because I set the `sandbox` attribute and didn't include all the right attributes. Since we're not too concerned about restricting janis, it's easiest to just remove the attribute entirely so there's no extra restrictions.
See more info on the [MDN iframe](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) page.
Implements cityofaustin/janis#100
=> Allow cookies to be set on preview

joplin/settings.py
We don't care so much about the `ALLOWED_HOSTS` in debug mode and it only causes pain when trying to develop
=> Allow any host in debug

fixtures/contacts.yaml, joplin/base/management/commands/loadcontent.py
The phone number field is still text, but we want to serve it in the API as JSON. As a workaround, we'll just load the phone number as a JSON string. Someday we'll properly separate individual fields, but today ain't that day.
Part of cityofaustin/techstack#207
=> Load phone number as JSON

joplin/base/management/commands/loadcontent.py, joplin/base/models.py, joplin/base/signals.py, scripts/serve-local.sh
Django looks in the DB to see what images are available. We're running into a weird situation where the DB says there are images (the data is persisted because it's in postgres), but the images aren't on the filesystem (because we're using docker).
If we blow away the rows in the DB, django will remove the files on the filesystem if they exist. Then we can happily load the images and everything will be in harmony.
Other detritus:
- No need to register the delete image hooks since that bug has been fixed in wagtail
- Don't set loglevel to debug locally so we don't get so much cruft on the screen
Fixes cityofaustin/techstack#473
=> Delete images before loading them

joplin/base/management/commands/loadcontent.py
The last language we use is the language that'll show up by default in the wagtail admin. Set `page.title` last as the english version so it shows up in english.
=> Set page.title last so it's in english

joplin/static/css/preview.css, joplin/templates/wagtailadmin/pages/edit.html
I widened the constants that were previously being used so the tabs could fit and more content could fit on the screen. Unfortunately this blocks some of the controls for editing so we might have to play with how this fits together. This seems like an OK start.
Fixes cityofaustin/techstack#467
Here's how things currently look:
=> Embed styleguide in edit page

joplin/base/models.py
lets us use one more heading tag (especially helpful for the OPO info page)
=> add h3 for info page

joplin/css/admin.scss, joplin/templates/wagtailadmin/base.html
in order to fix the timezone issue from https://github.com/cityofaustin/techstack/issues/1964, we need to be able to change the timezone for a user. Instead of passing around a secret URL for this I've made the account avatar and email in the top right corner link to the account settings page
=> 1964 account settings

joplin/base/wagtail_hooks.py
Fixes https://github.com/cityofaustin/techstack/issues/2181
We have a redundant icon for now, mainly because:
For some reason we have to re-make individual icons for menu items instead of pulling them from wagtail admin? WTH?
Also, it would appear the way we are constructing the menu could use refactoring. 
As it says in the docs: 
> Adding menu items should generally be done through the register_admin_menu_item hook instead - items added through construct_main_menu will be missing any associated JavaScript includes, and their is_shown check will not be applied.
http://docs.wagtail.io/en/v2.5.1/reference/hooks.html
This may also mean refactoring some of the url stuff we have too. There is a lot of crustiness lying around...
=> 2181 user account controls

joplin/users/models.py
Fixes https://github.com/cityofaustin/techstack/issues/1376
@briaguya we may want to test this more eventually 
I'm using this: 
https://docs.djangoproject.com/en/2.2/ref/models/querysets/#iexact
This should work for now. But I'm not sure how we'd handle sign-up/registration of emails. We have a unique validator there, but I'm not sure if that validator is also case sensitive? Another route to go might be casting all emails to lower() when making accounts for people, etc.
=> 1376 login case insensitive

README.md, app.Dockerfile, docker-entrypoint.sh, scripts/handle-migration-conflicts.sh, scripts/run-handle-migration-conflicts.sh
So the idea here:
* docker entrypoint is used every time we spin up a container
* so every time we run migrations....
* so _before_ that every time lets makemigrations, with the --merge flag to deal with conflicts
This should help catch missing migrations or conflicts when we merge to master. 
Cons:
* I'm not as familar of the overall build process, so not sure if this has unintended consequences?
* Migrations will look kinda messy, but I think this is more compatible than deleting/rolling back
* With this in mind, we could consider squashing all the migrations every time we ship a new major/minor version?
* I played around with adding the branch + commit hash to the name of the migration for reference, but I think this is overkill for now
=> add make migrations step that merges conflicts

joplin/base/templatetags/joplin_tags.py
related to https://github.com/cityofaustin/techstack/issues/2254 , this at least gets the right page loaded for each content type
=> re-write routes for styleguide pages

joplin/base/views/joplin_views.py
Ref: cityofaustin/techstack#2679
=> prevent page breaking when adding content that belongs to a department

joplin/api/schema.py, joplin/base/models/__init__.py, joplin/base/models/department_page.py, joplin/base/models/guide_page.py, joplin/base/models/information_page.py, joplin/base/models/janis_page.py, joplin/base/models/official_documents_page.py, joplin/base/models/service_page.py, joplin/base/models/topic_collection_page.py, joplin/base/models/topic_page.py
tested locally the backend and against a build of janis and nothing broke
since the model was abstract in the first place it dosent require a migration
https://austininnovation.slack.com/archives/G82KEHEQZ/p1565204354002600
Eric Sherman:chicago: 1:59 PM
@brian one question i did want to ask about code organization...i understand how we have the JanisBasePage inherit from the Page model, but any particualr reason why we have another point of inheritance from JanisBasePage to JanisPage? Couldn't we just add that method to JanisBasePage?
side-note, is that method even used/doing anything useful? it seemed related to the promote and search tabs which we dont even expose for a page
i'd love to either clean that up or document what the decision is there
Brian Smith 2:00 PM
I forget what exactly …
=> consolidate JanisBasePage and JanisPage into a single Abstract model

joplin/base/models/janis_page.py
Fixes: https://github.com/cityofaustin/techstack/issues/2732 
exposes a pretty obvious error in the janis_url function
This section probably deserves some refactoring, and some more nuanced handling. 
We could also bypass the problem (sorta) by making the field required for publish 
( related to https://github.com/cityofaustin/techstack/issues/2732 ) 
This PR at least logs the error and dosen't break joplin, so a user could go back and fix the problem without needing to ask a dev to change it via django shell ( which is what I did last time )
=> very basic error handling and logging

joplin/api/schema.py, joplin/base/models/department_page.py
This only covers a little bit of https://github.com/cityofaustin/techstack/issues/2855, but is required to ensure our OPO content doesn't need to change from what is currently in production.
=> add official document pages as an option for top services on dept pages

Pipfile, Pipfile.lock, deploy/requirements.txt
This should have character counts working even on nested items
** note how this is set up for packaging ** 
Deployed branches use the PyPi published version defined in requirements.text
Using Pipenv the library is tied to the _latest commit on master for that repo_. This makes testing or development a bit handier (just push a commit and run joplin locally)
changes/library is here if you're interested: https://github.com/cityofaustin/django-countable-field
=> uses new version of countable-field

joplin/css/editor.scss, joplin/js/EditPage/richTextPlaceholder.js
This will remove some unnecessary logs as well as fix a small typo 
- "placeolder" 👉"placeholder" 👍
=> Fixing typo and clearing logs

pull_request_guide.md, pull_request_template.md
This PR will make it so when we create a *new* PR the `pull_request_template.md` will be *automatically* placed in the description field (ie, *this* field). Yes, this is a very *Meta* PR...🤓.
- See the [markdown file](https://github.com/cityofaustin/joplin/blob/d2bfa2f3de718870b7c456a7b38737d06c7ae24d/pull_request_template.md) to view what would currently be the default template, as an outline. 
- Also, this is just a rough-draft, and I suspect maybe y'all will have things you'd like to add and remove. 
- OR, maybe the auto-fill outline isn't want we want🤷‍♂️. And, that's ok.
- I also created `pull_request_guide.md`, which is a more traditional markdown that is mainly used as a PR resource. Nothing automated there.  
Fixes #3025
* [Issue …
=> 3035 pull request template

joplin/base/models/information_page.py
Hide options from info pages until we decide if/how we're using it
https://github.com/cityofaustin/techstack/issues/3072
=> comment out info page options

joplin/base/views/joplin_search_views.py, joplin/settings.py, joplin/templates/wagtailadmin/pages/coa_header.html, joplin/templates/wagtailadmin/pages/index.html, joplin/templates/wagtailadmin/pages/search_header.html
1) The first commit changes where we exclude home and root, avoiding an extra for loop and making the query about 50% faster
2) I included the search input that works using AJAX. See comments on the PR. 
3) I added back the old header but in a more flexible way, cause it still may show up on some views. 
There were some other issues Bob and I discussed and raised, but we can turn those into follow up issues.
=> 2581 tweaks

joplin/base/views/joplin_search_views.py, joplin/settings.py
When we go to /admin or /admin/pages/search/ it'll now redirect us back to the login page if we're not properly authenticated.
* [Issue 3351](https://github.com/cityofaustin/techstack/issues/3351)
* And incidentally happens to fix [3339](https://github.com/cityofaustin/techstack/issues/3339)
- Go to https://joplin-pr-3351-login.herokuapp.com/admin. See that you are redirected to the login page rather than the zombie search page.
- Go to https://joplin-pr-3351-login.herokuapp.com/admin/pages/search. See that you are redirected to the login page rather than the zombie search page (this was the actual cause of the bug).
=> fix redirect to search home page

joplin/templates/wagtailadmin/pages/edit.html
turns out we just had some dom issues with the dropdown
https://github.com/cityofaustin/techstack/issues/3146
If we can see the unpublish button on the edit page we're good
* [Deployed Link](https://joplin-pr-3146-edit-page-unpub.herokuapp.com/)
=> 3146 - get unpublish back on the edit page

joplin/base/views/joplin_search_views.py, joplin/css/layouts/headers.scss, joplin/templates/wagtailadmin/pages/search_header.html, joplin/templates/wagtailadmin/pages/search_results.html, joplin/templates/wagtailadmin/shared/field.html
Issue: https://github.com/cityofaustin/techstack/issues/3363
Styling 
Behavior Issues
* "Changes you made may not be saved"
... Search for something by typing into search box 
- the page should update while you type (no need to hit enter or select a "search" icon.
Now, with the search results return, filter by content types
- The content type should now be filtered without an error message or alert. 
* [Deployed Link](https://joplin-pr-search-fixes.herokuapp.com/admin/pages/search/)
=> 3363 Main search alert & styling fixes

joplin/base/models/__init__.py, joplin/base/models/constants.py
Now we can embed videos
Part of https://github.com/cityofaustin/techstack/issues/3371
Janis PR: https://github.com/cityofaustin/janis/pull/611
Janis App: https://janis-3371-video-embeds.netlify.com/en/health-safety/health-records-certificates-2/birth-death-certificates/video/
Go to http://joplin-pr-3371-video-embeds.herokuapp.com/admin/pages/265/edit/#tab-content and see that adding a video works on https://janis-3371-video-embeds.netlify.com/en/health-safety/health-records-certificates-2/birth-death-certificates/video/
=> 3371 - Add embed to WYSIWYG_GENERAL

.circleci/scripts/build_image.sh, README.md, docker-compose.local_override.yml, docker-compose.migration_test_override.yml, docker-entrypoint.sh, joplin/db/system-generated/dummy.datadump.json, joplin/db/system-generated/dummy_datadump_metadata.txt, scripts/migration-test.sh
This is just to get us a start on having a way to manage dummy data dumps. The included datadump has one of each page type, with very minimal data. Janis master will build without errors using the included data, and all pages are published/linked in nav.
=> 3396 dummy data

joplin/api/content_type_map.py, joplin/api/schema.py
* Update site structure to include location pages
* Update page revisions to work with location pages
https://github.com/cityofaustin/techstack/issues/3535
[Janis Related Pull Request Link](https://github.com/cityofaustin/janis/pull/645)
Joplin edit: http://joplin-pr-3535-location-pages.herokuapp.com/admin/pages/278/edit/#tab-content
Janis Preview: https://janis-3535-location-page.netlify.com/en/preview/location/UGFnZVJldmlzaW9uTm9kZToyMzk5?CMS_API=https://joplin-pr-3535-location-pages.herokuapp.com/api/graphql
Janis live: https://janis-3535-location-page.netlify.com/en/location/faulk/
=> 3535 - location pages - api changes

joplin/locations/models.py
I commented out the line that was changing all the title fields to say Location name and left a note as to why.
https://joplin-pr-3622-title-fields.herokuapp.com/
=> 3622 "Location name" in content type title fields

joplin/css/pages/edit.scss
Zenhub Issue Link: https://app.zenhub.com/workspaces/techstack-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/3499
The display as fixed for the edit pages tab, was the culpret. So, that means we need to style them seperatly. I used the already existing id to target the ul (`#page-edit-form > ul`) so i can remove the fixed position of the *user* edit tabs👍
- And... some border issues needed to be cleaned up.
Deployed: https://joplin-pr-3499-floating-tab.herokuapp.com/
- Edit User Link: https://joplin-pr-3499-floating-tab.herokuapp.com/admin/users/3/#account
=> styling tabs speratly in page and user edit

joplin/templates/wagtailadmin/pages/search_results.html
This one is prettty self-explanatory. 
The modal wasn't opening because the elements weren't on the results page to open onto.
=> make sure the modal template is included on results page

README.md
Postgres on heroku has been upgraded for staging in production. 
This PR is meant to open discussion on whether to revisit our process for syncing data to staging from prod. The heroku CLI does provide lots of handy features for syncing data, and an example command is proposed here being added to the Readme. 
Other TODOs; things to check:
* By default, if a database is missing our build process attaches a hobby-tier PG instance. 
However, I might suggest for staging and prod that we _don't_ manually drop the database for staging or prod, unless others can think of good or justifiable reasons where we'd want to do that. This could cause data loss and a bad user experience if someone happens to be using the app while you are dropping the database. 
Running Django's ```loaddata``` command …
=> new step for syncing prod data to staging

joplin/events/models.py, joplin/js/editor.js
When the "event is free" checkbox is checked, the fees are hidden.
https://github.com/cityofaustin/techstack/issues/3874
1. Go here: http://joplin-pr-3874-hide-fees.herokuapp.com/admin/pages/362/edit/#tab-content
2. See fees are hidden
3. Play with event is free checkbox and watch fees show/hide
=> 3874 - hide fees when event is free (js)

joplin/css/pages/edit.scss
Fixes a style bug introduced when we moved some divs around for the publish error messages. 
So note! some of the class names on the page edit view overlap with the class names on the snippet edit view. 
https://joplin-pr-3977-snippet-labels.herokuapp.com/admin/snippets/base/contact/1/
check a snippet, check that you can see the whole title wrapper per field
=> 3977 snippet labels

joplin/base/views/joplin_search_views.py, joplin/templates/wagtailadmin/pages/search_results.html
https://github.com/cityofaustin/techstack/issues/3974
1. Go to https://joplin-pr-3974-list-order.herokuapp.com/admin/pages/search/
2. See that it's sorting by last updated
3. Try playing with page filters and searching and see if the pages are ordered as expected
=> 3974 - clean up page ordering

README.md, joplin/api/schema.py
Unpublished pages are currently showing up in site structure, which was breaking my events pages query on janis (only getting live pages)
This PR changes it so we filter on live pages, not getting all pages. 
note from @briaguya: looks like this should handle https://github.com/cityofaustin/techstack/issues/4027
https://joplin-pr-3818-event-home2.herokuapp.com/
=> only get live pages in site structure

.circleci/vars/heroku_pr_vars.py, .gitignore, joplin/js/editor.js, joplin/settings.py
Sometimes when we enter in an address for a location, the autosuggest will say an incorrect zip code. 
800 Guadalupe's zipcode is 78701.
For now, we are commenting out the autosuggest until they fix it.
=> 3943 - places incorrect zip code

joplin/base/templatetags/joplin_tags.py
Links location pages to appropriate section in the styleguide. 
At the moment, the nav for the styleguide is hard-coded, so this:
https://github.com/cityofaustin/digital-services-style-guide/commit/189662fd7acf69d5e5a77011cd4178a40e870ef5
Is the accompanying change to make the section browseable inside joplin
=> add location page to styleguide

joplin/joplin_UI/application_banner.scss, joplin/templates/joplin_UI/application_banner.html
This is a patch for https://github.com/cityofaustin/joplin/pull/586
The new SVG file for the dropdown arrow wasn't pulling in environment directory variables. Which pulled a 404 when adding the image on staging (and probably prod)
Test Link: https://joplin-pr-dropdown-fix.herokuapp.com/
- login 
- click lamp.
- see arrow properly display... NOT like this 
HOWEVER: we won't know if this worked until merged into staging.
----
* I also forgot to remove the blue hover color in the UI, so i snuck that in here...
=> fixing svg directory issue

joplin/base/views/joplin_search_views.py
instead of filtering out magic number page ids let's filter out using a magic number content type id!
https://github.com/cityofaustin/techstack/issues/4143
=> content type filtering for search

.circleci/vars/branch_overrides.py, joplin/base/views/joplin_search_views.py, joplin/base/views/new_page_from_modal.py, joplin/pages/home_page/migrations/0002_create_homepage.py, joplin/pages/information_page/factories.py, joplin/pages/topic_collection_page/factories.py, joplin/pages/topic_page/factories.py
Issue: cityofaustin/techstack#4148
The first step for multiple sites is having 1 site. We had the create_homepage migration in Joplin v2, and now we have it here. Having a custom homepage type will help many things, like moving site_settings into the home page.
See if you can make a page. If this doesn't break anything, we should be good to go.
https://joplin-pr-4148-add-homepage.herokuapp.com/
=> Issue 4148: use custom home_page content type

.circleci/config.yml, .circleci/vars/branch_overrides.py, joplin/groups/factories.py, joplin/pages/base_page/tests.py
https://github.com/cityofaustin/techstack/issues/4142
Faker randomly generates names for us. Unfortunately, some of those random names turn up duplicates. This was problematic for our DepartmentFactory because it has a uniqueness requirement on the "name" field. Fortunately we could use factory.Sequence() to guarantee uniqueness. This is basically how people do it in the real world: https://github.com/FactoryBoy/factory_boy/issues/305
=> Issue 4142: fix spontaneous pytest breakings

joplin/api/schema.py
makes it so this works:
```
{
allPages {
edges {
node {
janisUrls
eventpage {
id
}
locationpage {
id
}
departmentpage {
id
}
topiccollectionpage {
id
}
janisbasepagewithtopiccollections {
topicpage {
id
}
}
janisbasepagewithtopics {
guidepage {
id
}
servicepage {
id
}
informationpage {
id
}
officialdocumentpage {
id
}
formcontainer {
id
}
}
}
}
}
}
```
=> v3 api - add nodes for pages with topics and pages with topic collections

joplin/importer/queries.py
As a prelude to making an importer for department groups/pages, I decided to clean up our importer's graphql queries. This eliminates copypasta in our graphql queries.
The downside of eliminating copypasta is that we can no longer copypasta those queries right into Insomnia or graphiql, which is kind of nice for testing. So I created a helper function that will print the complete querystrings into the console for you. Test with: `pipenv run python joplin/importer/queries.py`
=> clean up importer queries

.circleci/vars/branch_overrides.py, README.md, README/testing.md, joplin/css/pages/edit.scss, joplin/groups/factories.py, joplin/groups/fixtures/__init__.py, joplin/groups/fixtures/helpers/create_fixture.py, joplin/groups/fixtures/test_cases/title.py, joplin/pages/base_page/factories.py, joplin/pages/base_page/tests.py, joplin/pages/department_page/tests.py, joplin/pages/information_page/factories.py, joplin/pages/service_page/factories.py, joplin/pages/topic_collection_page/factories.py, joplin/pages/topic_page/factories.py, joplin/publish_preflight/tests/utils/make_form.py, joplin/settings.py, joplin/templates/wagtailusers/users/create.html, joplin/templates/wagtailusers/users/edit.html, joplin/users/forms.py, joplin/users/js/index.js, joplin/users/templatetags/user_tags.py, joplin/users/tests/conftest.py, joplin/users/tests/tests.py, joplin/users/tests/utils/make_user_form.py, joplin/users/views/users.py, joplin/webpack.base.js
Oh cool we got a twofer.
- https://github.com/cityofaustin/techstack/issues/4046: Editors/moderators MUST belong to a department
- https://github.com/cityofaustin/techstack/issues/4047: Create new user: Separate editor/moderator from departments
If you don't believe me, try it here:
https://joplin-pr-4047-separate-groups.herokuapp.com/admin/users/
Behold, roles and departments are separated, per cityofaustin/techstack#4047
And, it won't let you save if you don't choose both a role and a department in accordance with cityofaustin/techstack#4046
=> Issue 4047: separate roles and departments when creating new user

.circleci/vars/branch_overrides.py, joplin/api/schema.py
Janis needs topic collections to be able to query their topics and those topics' top pages. 
https://joplin-pr-4223-resolve-tc.herokuapp.com/admin/pages/search/
https://joplin-pr-4223-resolve-tc.herokuapp.com/api/graphql
"id" : "VG9waWNDb2xsZWN0aW9uTm9kZTo1"
```
query getTopicCollectionTopics($topicCollection: ID) {
topicCollectionTopics(topicCollection: $topicCollection) {
edges {
node {
page {
topicpage {
id
title
topPages {
edges {
node {
id
title
}
}
}
}
}
}
}
}
}
```
=> 4223 - topic collections resolve their topics and top pages

joplin/importer/queries.py, joplin/importer/tests.py, joplin/pages/location_page/factories.py, joplin/pages/location_page/tests.py
* When importing a location page, we also get service hours imported
* Actually connect the correct service page to the location page
https://github.com/cityofaustin/techstack/issues/4219
see tests pass
try importing location pages with related services that have hours
=> 4219 import location page related service hours

.circleci/vars/branch_overrides.py, joplin/pages/guide_page/models.py
https://app.zenhub.com/workspaces/techstack-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/4266
- Change the requirement to "contact" from "contacts"
- It's also a FieldPublishRequirement now instead of a many to many sort of RelationPublishRequirement
http://joplin-pr-4266-guide.herokuapp.com/
- Test by building and publishing a guide page. It should work instead of breaking.
=> fix publishing on guide pages

README/add_new_content_type.md, joplin/importer/queries.py, joplin/pages/base_page/fixtures/helpers/page_type_map.py, joplin/pages/form_container/factories.py, joplin/pages/form_container/tests.py
https://github.com/cityofaustin/techstack/issues/4260
Here's a good example of all we need to import a new page_type.
You can test that it works by importing a form_container page.
https://joplin-pr-4260-import-form.herokuapp.com/
=> 4257: import form_container

joplin/pages/service_page/factories.py, joplin/pages/service_page/fixtures/__init__.py, joplin/pages/service_page/fixtures/helpers/components.py, joplin/pages/service_page/fixtures/test_cases/kitchen_sink.py, joplin/pages/service_page/fixtures/test_cases/step_with_options.py, joplin/pages/service_page/tests.py
When trying to import https://janis.austintexas.io/en/preview/services/UGFnZVJldmlzaW9uTm9kZTozMjM1 in an effort to test out associated department importing, I found that importing steps with options was broken. This address that by:
* adding fixture data for step with options
* adding a test for steps with options
* making that test pass by updating the Service Page factory
=> Steps with options

.circleci/vars/branch_overrides.py, joplin/importer/queries.py, joplin/importer/tests.py, joplin/pages/information_page/tests.py
When importing pages, we now query for live and pass it along to the factories.
https://github.com/cityofaustin/techstack/issues/4274
* go here https://joplin-pr-4274-are-we-live.herokuapp.com/
* Try importing a page that's live and a page that's a draft
* See that the live page is imported as live and the draft is imported as a draft
=> 4274 are we live? (import live/draft with importer)

.circleci/vars/branch_overrides.py, joplin/api/schema.py
This changes our  allPages API to include page types and descriptions for page indexes. 
Example graphql query used to build search  indexes.
- I modified the basepage a bit to allow for `page types` and `short descriptions` and filtered out non-`live` pages. 
```
{
allPages(live: true) {
edges {
node {
id
title
janisUrls
pageType
summery
}
}
}
}
```
To Test: 
- See API queries include all current page data deployed branch's  in Joplin.
Deployed: http://joplin-pr-api-pagetype-descrip.herokuapp.com
URL query:  http://joplin-pr-api-pagetype-descrip.herokuapp.com/api/graphql/?query={%20allPages(live:%20true)%20{%20edges%20{%20node%20{%20id%20title%20janisUrls%20pageType%20summery%20}%20}%20}%20}
Graphiql: http://joplin-pr-api-pagetype-descrip.herokuapp.com/api/graphiql/#query=%7B%0A%20%20allP …
=> Api page type and description

joplin/importer/create_from_importer.py, joplin/pages/home_page/models.py, joplin/pages/location_page/fixtures/__init__.py, joplin/pages/location_page/fixtures/test_cases/live_city_hall.py, joplin/pages/location_page/fixtures/test_cases/live_library.py, joplin/pages/service_page/factories.py, joplin/pages/service_page/fixtures/__init__.py, joplin/pages/service_page/fixtures/helpers/components.py, joplin/pages/service_page/fixtures/test_cases/kitchen_sink.py, joplin/pages/service_page/fixtures/test_cases/step_with_1_location.py, joplin/pages/service_page/fixtures/test_cases/step_with_2_locations.py, joplin/pages/service_page/management/commands/load_test_service_pages.py, joplin/pages/service_page/tests.py
https://github.com/cityofaustin/techstack/issues/4275
Alright, here's the deal with importing steps with location pages.
Take a look at the test fixtures I made. That's how our ServicePage model's streamfield wants to get a step with a location_page. All it wants is the primary key of your location page. It's a lot like adding a location_page onto an event_page
So that works great if we just want to make a fixture ourselves. But its tricky when we want to import a service page. Our API for steps does not return enough data to fully create/import a new location_page. There is a path to making this work. This guy laid some good groundwork that we could use to make resolvers for streamfields that could connect to LocationPageNodes instead of being a generic Scalar. …
=> 4275 step with location

.circleci/vars/branch_overrides.py, joplin/pages/home_page/models.py
Homepage is requiring a title & slug in order for the page to update and publish/save. We can manually add a slug, but don't have it exposed to add a title. 
We are excluding the title from required fields: 
https://github.com/wagtail/wagtail/blob/master/wagtail/core/models.py#L447
https://github.com/django/django/blob/master/django/db/models/base.py#L1193
https://joplin-pr-4282-homepage.herokuapp.com/admin/pages/search/
=> 4282 homepage

joplin/api/schema.py
Add a few quick resolvers in the schema to help us get info we need to do a full import.
This [graphql query](http://joplin-pr-latest-revision.herokuapp.com/api/graphiql#query=%7B%0A%09allPageRevisions(last%3A20)%20%7B%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20isLatest%0A%20%20%20%20%20%20%20%20isLive%0A%20%20%20%20%20%20%20%20pageType%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) shows off the benefits quite well
=> Add live and latest to page revision query

.circleci/vars/branch_overrides.py, joplin/importer/page_importer.py, joplin/pages/service_page/fixtures/__init__.py, joplin/pages/service_page/fixtures/helpers/components.py, joplin/pages/service_page/fixtures/test_cases/placeholder_for_internal_links.py, joplin/pages/service_page/fixtures/test_cases/step_with_internal_links.py, joplin/pages/service_page/tests.py, joplin/pages/topic_page/fixtures/__init__.py, joplin/pages/topic_page/fixtures/test_cases/title.py
When importing pages with internal links, we now try to recreate the internal links by matching slugs to previously imported pages. If we don't find a page with a matching slug, the link is set to a placeholder and the imported page is kept in draft state.
https://github.com/cityofaustin/techstack/issues/4288
* go here: http://joplin-pr-4288-internal-links.herokuapp.com/admin/pages/search/
* try importing a page with a rich text internal link to a page you've already imported
* see that the link is set as internal and to the correct page
=> 4288 internal links

.circleci/vars/branch_overrides.py, joplin/importer/create_from_importer.py, joplin/pages/service_page/tests.py
When importing, we get english fallback values from the API when there isn't a localized value. This is great for Janis, but not the best for importer. This PR addresses that by checking to make sure the english and spanish values aren't equal when combining dictionaries.
https://github.com/cityofaustin/techstack/issues/4281
* go here https://joplin-pr-4281-spanish.herokuapp.com/admin/login/
* import a page
* see that it doesn't fill the spanish fields with english content
=> 4281 don't import english into spanish fields

joplin/settings.py
Janis PR: https://github.com/cityofaustin/janis/pull/738
I guess full site builds weren't working locally, so I fixed it.
Doing that led to redirecting http to https. That seems like a good security thing. I followed these directions: https://help.heroku.com/J2R1S4T8/can-heroku-force-an-application-to-use-ssl-tls
Click here:
http://joplin-pr-4309-topics.herokuapp.com/admin/pages/search/ 
It'll redirect you here:
https://joplin-pr-4309-topics.herokuapp.com/admin/pages/search/
=> allow local full site builds; redirect to https

.circleci/vars/branch_overrides.py, joplin/importer/create_from_importer.py, joplin/pages/service_page/fixtures/__init__.py, joplin/pages/service_page/fixtures/helpers/components.py, joplin/pages/service_page/fixtures/test_cases/step_with_location_first_then_basic_step.py, joplin/pages/service_page/tests.py
When importing steps with locations, we ran into an issue with localization. Our logic was leading to `steps_es` making it into our final `combined_dictionary` without having been processed.
This PR fixes that
https://github.com/cityofaustin/techstack/issues/4311
* go here https://joplin-pr-4311-stream-block-er.herokuapp.com/admin/pages/search/
* try importing https://janis.austintexas.io/en/preview/services/UGFnZVJldmlzaW9uTm9kZTozNDc4
* watch it work
=> Spanish steps with locations

.circleci/vars/branch_overrides.py, joplin/api/schema.py
If a page doesn't have janis instances (in draft or no departments yet), the preview query was giving an error `Cannot return null for non-nullable field`. But an empty `{}` is fine. 
In conjunction with https://janis-v3-4302-make-janis-preview.netlify.app/, you can preview locations, service pages in draft (ex: 
https://joplin-pr-4302-janis-preview.herokuapp.com/admin/pages/16/edit/#tab-content) etc. 
Note!!
This page did not preview
https://joplin-pr-4302-janis-preview.herokuapp.com/admin/pages/27/edit/#tab-content 
because it did not provide the CMSPreview with an id.
=> Resolve Janis Preview Instances

joplin/importer/create_from_importer.py
We were trying to pass `physical_location_photo` data to the location page factory without doing anything to it. This caused location pages with images to fail to import.
This allows the page to import without the image instead of failing to import entirely.
https://github.com/cityofaustin/techstack/issues/4317
I already merged this into import-everything. The location page from the original error is here now https://joplin-pr-import-everything.herokuapp.com/admin/pages/191/edit/#tab-content
=> 4317 until we support importing images don't try to import them

joplin/base/signals/janis_build_triggers.py, joplin/base/signals/publish_v3.py
Issue: https://github.com/cityofaustin/publisher/pull/8
- Remove the old aws_publish invocation, use new Publisher for staging and production
=> Issue 4092: use publish_v3 for staging and production

joplin/users/forms.py
https://github.com/cityofaustin/techstack/issues/4371
Alright. There was a bug with editing anything related to your own user. I made a custom user form handler. And I didn't realize that is_superuser won't be part of cleaned_data if you're editing your own user. I wrote more in the code comments. It might be excessive, but I didn't want there to be mystery logic in our code.
https://joplin-pr-4371-user-bugs.herokuapp.com/
Make a user on the PR deployment. Then try to edit that user while you're logged in as that same issue. You should have no problem changing your password, name, or department.
=> Issue 4371: fix bugs with editing your own user

joplin/api/schema.py
https://github.com/cityofaustin/techstack/issues/4449
query https://joplin-pr-4449-slug-es.herokuapp.com/api/graphql with this and switch your headers to en/es, see that we get the english slug every time
```
{
allPages {
edges {
node {
janisbasepagewithtopiccollections {
topicpage {
topPages {
edges {
node {
slug
}
}
}
}
}
}
}
}
}
```
=> until we get localized urls working just send over the english slug

joplin/base/templatetags/joplin_tags.py, joplin/conftest.py, joplin/js/CreateContentModal/ChooseTypeStep.js, joplin/js/CreateContentModal/index.js, joplin/templates/wagtailadmin/pages/search_header.html
Authors should not be able to make topics or topic collections, so that link is hidden from the create content modal. 
I registered an inclusion tag to be able to check if the user is in the editors groups or not. 
https://joplin-pr-4400-topic-prevent.herokuapp.com/admin/pages/search/
login as admin. click create content modal, see the option to make a topic or topic collection
login as editor, follow the same steps and you shouldnt be able to see the topic and topic collection
login: editor@austintexas.io
pw: e
=> 4400 Prevent editors/authors from creating topics and topic collections

joplin/templates/joplin_UI/messages/unpublishing.html, joplin/templates/wagtailadmin/pages/confirm_unpublish.html
https://github.com/cityofaustin/techstack/issues/4541
Just a couple Joplin UX bugs.
They work now.
https://joplin-pr-4561-queue-bugs.herokuapp.com/admin/pages/search/
Unpublish a live page.
It should redirect back to the edit page.
And it should have an "unpublishing" banner at the top that you can close.
=> Issue 4561: fix unpublishing UX bugs

joplin/base/views/publish_succeeded.py, joplin/pages/base_page/fixtures/helpers/create_fixture_map.py, joplin/pages/base_page/models.py
https://github.com/cityofaustin/techstack/issues/4559
Ok, there was this crazy thing where page_statuses weren't synced up correctly. Like, on the Content List View, it'd say "oh yeah your page is definitely 'Unpublishing' no worries." But then when you clicked on it, it'd be all like "No, your page is in 'draft' status." And I'd be like "But aren't you still working on 'Unpublishing' it? That's what the Content List View says." And the edit page is still all like "Nah bro don't know what you're talking about."
How could this be?
I'll tell you how.
There are 2 places where information for a page is saved. 
1. The Page itself. `page = Page.objects.get(id=page_id)`
1.5. (But really the stuff we care about is in the specific model for your content_type) `page = page.specific`
2. The …
=> fix inconsistent revision publish statuses

joplin/api/schema.py, joplin/pages/official_documents_page/factories.py
When the site builds, test it with:
```
query getThing($id: ID) {
officialDocumentCollectionDocuments(officialDocumentCollection: $id, orderBy: "-page__date") {
edges {
node {
id
officialDocumentCollection {
id
}
page {
id
title
}
}
}
pageInfo {
hasNextPage
endCursor
}
}
}
```
=> allow orderBy: "-page__date" on officialDocumentCollectionDocuments

.circleci/vars/branch_overrides.py, joplin/api/schema.py, joplin/base/management/commands/make_translation_report.py, joplin/settings.py, scripts/sync_data.sh
https://github.com/cityofaustin/techstack/issues/4621
Previews for Official Document Collections should now display their child documents within Preview. We changed the api.schema to return the document url within DocumentNodeDocument.
Bonus thing that got added! There's now an a script to copy data between Joplin environments, including documents.
Janis PR: https://github.com/cityofaustin/janis/pull/817
https://joplin-pr-4621-preview.herokuapp.com/admin/pages/319/edit/?next=/admin/pages/319/edit/#tab-content
We should be able to see child official documents in the mobile preview.
=> 4621 preview

joplin/api/schema.py
Adds two very important things: 
- Official Document Pages on Janis need to know what department they are under, I forgot to include that when creating the officialDocumentPageNode 
- Return OfficialDocumentPageNode in the Revision Query in order for previews to work
[Janis Related Pull Request Link](https://github.com/cityofaustin/janis/pull/820) 
https://joplin-pr-4591-janis-docs.herokuapp.com/admin/pages/search/
=> 4591 - add department resolver to official document pages

joplin/templates/wagtailimages/images/index.html
Yesterday before I merged my changes, I decided to add some more documentation. However, I didnt test after I did that, because I erroneously thought that comments wouldn't break anything. 
I was wrong. Templates have to have the `{% extends %}` block at the beginning of the file or else it won't load and does an internal server error. 
So I have learned:
do not assume comments wont change behavior. 
don't change things after QA has approved and expect it to still work
pay more attention during your 9pm code merges
also I learned how to revert pull requests and how to revert command line merges and which one is easier to do. (pull requests)
https://joplin-pr-fix-image-bug.herokuapp.com/admin/pages/search/
click images on side bar, it should load and not fail.
admin/x to sign in
=> fix bug I introduced - move comment in file

Pipfile, Pipfile.lock, docker-entrypoint.sh, joplin/api/schema.py, joplin/base/views/site_search.py, joplin/pages/base_page/models.py, joplin/pages/event_page/models.py, joplin/pages/location_page/models.py, joplin/pages/official_documents_page/models.py, joplin/pages/topic_page/models.py, joplin/settings.py, joplin/urls.py
Issue: https://github.com/cityofaustin/techstack/issues/5052
Janis PR: https://github.com/cityofaustin/janis/pull/887
Now we have live keyword filtering. Both on the SearchPage and the OfficialDocumentCollectionPage. You enter a word. It'll query a new route called site_search on your CMS_API. It'll search through any field that you want to query (title, summary, body, etc.). And it'll return the exact page of results that you want. How cool!
I wrote notes for potential improvements to make from here in our Search v2 epic: https://github.com/cityofaustin/techstack/issues/4762
Check it out!
=> Issue 5052: site_search view

.circleci/scripts/check_app_status.py, joplin/conftest.py, joplin/importer/tests.py, joplin/pages/department_page/tests.py, joplin/pages/event_page/tests.py, joplin/pages/form_container/tests.py, joplin/pages/information_page/tests.py, joplin/pages/location_page/tests.py, joplin/pages/service_page/tests.py
Commenting out / marking "do not run" on importer tests, since they take time and we don't use importer on typical branches. 
If for some reason we bring back importer (turbo janis to prod janis for example), we can include the tests again.
=> 4907 remove importer tests

joplin/pages/event_page/models.py
After the event location names were updated, we needed to update the keys searched for in the search results. Also location names are handled in search on the joplin, but they are parsed on the frontend for general events display. I changed the name on the search results to prevent confusion/breaking on the frontend.
Virtual Events location gets returned based on language. 
[Janis Related Pull Request Link](https://github.com/cityofaustin/janis/pull/908)
https://joplin-pr-5054-events-search.herokuapp.com/admin/pages/search/
I have added some events to the joplin, see that you can search for them in janis:
https://janis-v3-5054-events-search.netlify.app/en/search/?page=1&q=party
admin@austintexas.io pw:x
=> 5054 update search

joplin/pages/official_documents_page/models.py
OPO needs to be able to bold type in the description. Adds it as an option for the rich text field. 
https://joplin-pr-5089-bold-rtf.herokuapp.com/admin/pages/27/edit/#tab-content
and there is a janis connected: https://janis-v3-5089-bold-rtf.netlify.app/
https://janis-v3-5089-bold-rtf.netlify.app/kitchen-sink-department/what-a-bold-document/
=> 5089 - add bold to rtf on official doc pages
